name: check_and_fix
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 9.0.0+9

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  permission_handler_platform_interface: ^3.9.0
  geolocator: ^9.0.2
  file_picker: ^5.2.11
#  flutter_blue: ^0.8.0
  record: ^4.4.4
  image_picker: ^0.8.7+4
  contacts_service: ^0.6.3
  camera: ^0.10.4
  wifi_scan: ^0.4.0+1
  table_calendar: ^3.0.9
#  photo_manager: ^2.6.0
  flutter_easyloading: ^3.0.5
  http: ^1.1.0
  uuid: ^3.0.7
  mobile_number: ^2.1.1
  fk_user_agent: ^2.1.0
  hive: ^2.2.3
  path_provider: ^2.1.0
  rich_console: ^1.0.6
  flutter_riverpod: ^2.1.3
  call_log: ^4.0.0
  flutter_sms_inbox: ^1.0.3

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  file_manager: ^1.0.2
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true
