name: files_sync
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  stacked_firebase_auth: ^2.19.4
  universal_platform: ^1.0.0+1
  sqflite: ^2.3.0

  contacts_service: ^0.6.3
  call_log: ^4.0.0
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
