// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTkl2mB3KgMrAJuwv8nZQWJ3oFkiWRuMM',
    appId: '1:615536036973:web:f97f85eb6e2b2efbb34364',
    messagingSenderId: '615536036973',
    projectId: 'phone-backup-free',
    authDomain: 'phone-backup-free.firebaseapp.com',
    storageBucket: 'phone-backup-free.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv66Klp6GB_kWy_uuPYxNbuxsnpyIQSM8',
    appId: '1:615536036973:android:3ec73d6ad50defb8b34364',
    messagingSenderId: '615536036973',
    projectId: 'phone-backup-free',
    storageBucket: 'phone-backup-free.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-nrlT33W8aGipVcn43JB1o5fPMV3s5g',
    appId: '1:615536036973:ios:357d100da14da394b34364',
    messagingSenderId: '615536036973',
    projectId: 'phone-backup-free',
    storageBucket: 'phone-backup-free.appspot.com',
    iosBundleId: 'com.biton.phone-backup',
  );
}
